# Meta Data for SEO

## Homepage
title = "FSC Utilities Plugin"
titleSeparator = "-"
titleAddition = "An input assistance for Vertafore FSC Rater CA"
description = "FSC Utilities Plugin is an input assistance software used together with FSC Rater."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "thiennguyenpro"
twitterCreator = "thiennguyenpro"
facebookAuthor = "thiennguyenpro"
facebookPublisher = "thiennguyenpro"
ogLocale = "en_US"

## JSON-LD
schemaType = "Thien Nguyen Productions"
schemaLogo = "thiennguyen-logo-150x150.png"
schemaTwitter = "https://twitter.com/thiennguyenpro"
schemaLinkedIn = "https://www.linkedin.com/in/thiennguyen1993/"
schemaGitHub = "https://github.com/thiennguyen93"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.thiennguyenpro.com/\">Thien Nguyen Productions</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/thiennguyen93/fsc-utilities/"
editPage = true
